language:
  - node_js

node_js:
  - lts/*

install:
  - npm install -g grunt-cli
  - npm install

script:
  - grunt jasmine

notifications:
  slack:
    rooms:
      - tnawebteam:C2GnodnLsxhwwGvr0xAcajzc#code-builds
